### ISSUE TITLE
Support subnet attributes in `NodeInfo`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-api-go#356]
* Blocked by https://github.com/nspcc-dev/neofs-api-go/issues/355
 
## Task

- [ ] Re-compile https://github.com/nspcc-dev/neofs-api/issues/181.
- [ ] Define format of subnet attribute key and add the function to calculate it from subnet ID.
- [ ] Define constant values of subnet  attribute.
